#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path:     /
    controller: App\Controller\DefaultController::index 
    
posts:
    path:     /posts
    controller: App\Controller\DefaultController::posts 

post:
    path:     /post/{slug}
    controller: App\Controller\DefaultController::post 
    
archive:
    path:     /archives
    controller: App\Controller\DefaultController::archives 
    